// Generated by CoffeeScript 1.4.0
/*
Module dependencies.
*/

var app, express, http, path, routes, user;

express = require("express");

routes = require("./routes");

user = require("./routes/user");

http = require("http");

path = require("path");

app = express();

app.configure(function() {
  app.set("port", process.env.PORT || 3000);
  app.set("views", __dirname + "/views");
  app.set("view engine", "jade");
  app.use(express.favicon());
  app.use(express.logger("dev"));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  return app.use(express["static"](path.join(__dirname, "www")));
});

app.configure("development", function() {
  return app.use(express.errorHandler());
});

app.get("/", routes.signup_step1);

app.get("/signup/step1*", routes.signup_step1);

app.get("/signup/step2*", routes.signup_step2);

app.get("/users", user.list);

http.createServer(app).listen(app.get("port"), function() {
  return console.log("Express server listening on port " + app.get("port"));
});
