// Generated by CoffeeScript 1.4.0

exports.home = function(req, res) {
  return res.render("home", {
    title: "Spyre"
  });
};

exports.signin = function(req, res) {
  return res.render("signin", {
    title: "Spyre"
  });
};

exports.signup = function(req, res) {
  return res.render("signup", {
    title: "Spyre"
  });
};

exports.onboarding = function(req, res) {
  return res.render("onboarding", {
    title: "Spyre"
  });
};
