// Generated by CoffeeScript 1.4.0

exports.home = function(req, res) {
  return res.render("home", {
    title: "Spyre"
  });
};

exports.stats = function(req, res) {
  return res.render("stats", {
    title: "Stats"
  });
};

exports.settings = function(req, res) {
  return res.render("settings", {
    title: "Settings"
  });
};

exports.signin = function(req, res) {
  return res.render("signin", {
    title: "Signin"
  });
};

exports.signup = function(req, res) {
  return res.render("signup", {
    title: "Spyre"
  });
};

exports.onboarding_1 = function(req, res) {
  return res.render("onboarding", {
    title: "Spyre",
    step: 1
  });
};

exports.onboarding_2 = function(req, res) {
  return res.render("onboarding", {
    title: "Spyre",
    step: 2
  });
};

exports.onboarding_3 = function(req, res) {
  return res.render("onboarding", {
    title: "Spyre",
    step: 3
  });
};

exports.onboarding_4 = function(req, res) {
  return res.render("onboarding", {
    title: "Spyre",
    step: 4
  });
};

exports.onboarding_5 = function(req, res) {
  return res.render("onboarding", {
    title: "Spyre",
    step: 5
  });
};
